import Count from '@/components/Count';
import React from 'react'

export const metadata = {
    title: "About page",
    description: "Generated by create next app",
};

export default function About() {


    return (
        <div>
            <Count />
        </div>
    )
}
