import React from 'react'

export const metadata = {
    title: "Contact page",
    description: "Generated by create next app",
};

export default function Contact() {
    return (
        <div>Contact</div>
    )
}
